# This file was generated by GoReleaser. DO NOT EDIT.
cask "coprem" do
  version "0.3.14"

  on_macos do
    on_intel do
      sha256 "53d137c4f80c19ff3f9e2f179d65ff03caa0937ea0f5bb74d5fc5e0b1b673d3c"
      url "https://github.com/bariiss/coprem/releases/download/v#{version}/coprem_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f6b38eae16f83d2a3278dce318af71422d96dc7b4e9e872caf436e879d234a6d"
      url "https://github.com/bariiss/coprem/releases/download/v#{version}/coprem_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7fbf4cf99289dd28a9332ddab62b56f5f04b475ecbb6ef284bc7b4fd1e7b3c58"
      url "https://github.com/bariiss/coprem/releases/download/v#{version}/coprem_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b3150ecac1d909e4f5e2a18d24f8070fd28fe81b5468599f544ccf544c4ec534"
      url "https://github.com/bariiss/coprem/releases/download/v#{version}/coprem_#{version}_linux_arm64.tar.gz"
    end
  end

  name "coprem"
  desc "GitHub Enterprise Copilot premium-request analytics CLI"
  homepage "https://github.com/bariiss/coprem"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "coprem"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/coprem"]
    end
  end

  # No zap stanza required

end
