# This file was generated by GoReleaser. DO NOT EDIT.
cask "coprem" do
  version "0.3.18"

  on_macos do
    on_intel do
      sha256 "8aa4818fa6c297ba869e45a9e267f96598eb22a4fc97807234e073857c206a8d"
      url "https://github.com/bariiss/coprem/releases/download/v#{version}/coprem_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e26b73450a0c914eff664415622caad1eb8fc69d6099ac017e9cf4b6b8c0fd7e"
      url "https://github.com/bariiss/coprem/releases/download/v#{version}/coprem_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8562ec50843d8cf859b129f5fdc95df4f2cc8baaaf1a22f82ad6bf5786ab4a2c"
      url "https://github.com/bariiss/coprem/releases/download/v#{version}/coprem_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c494a6f53657738a864765a10d62488f5f33183babafb0ac0999d6a4ab8c9f23"
      url "https://github.com/bariiss/coprem/releases/download/v#{version}/coprem_#{version}_linux_arm64.tar.gz"
    end
  end

  name "coprem"
  desc "GitHub Enterprise Copilot premium-request analytics CLI"
  homepage "https://github.com/bariiss/coprem"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "coprem"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/coprem"]
    end
  end

  # No zap stanza required

end
