# This file was generated by GoReleaser. DO NOT EDIT.
cask "coprem" do
  version "0.3.13"

  on_macos do
    on_intel do
      sha256 "7ed479176a2fd789190c9dec65ee544a286d06cb6978d68efffe3cb3fbfab984"
      url "https://github.com/bariiss/coprem/releases/download/v#{version}/coprem_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e5fbe919445132db218d7c0ec71d62e37cea10737e0bc419d4869be2f155412f"
      url "https://github.com/bariiss/coprem/releases/download/v#{version}/coprem_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dff6f25394091e4cf179afbef753a72950572501e037596a91334829b4a06575"
      url "https://github.com/bariiss/coprem/releases/download/v#{version}/coprem_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7cc865ca807fd1b082369d8bc039af034e1311ee376b9733be6c283d5d963108"
      url "https://github.com/bariiss/coprem/releases/download/v#{version}/coprem_#{version}_linux_arm64.tar.gz"
    end
  end

  name "coprem"
  desc "GitHub Enterprise Copilot premium-request analytics CLI"
  homepage "https://github.com/bariiss/coprem"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "coprem"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/coprem"]
    end
  end

  # No zap stanza required

end
